// var nome =  window.prompt("Qual é seu nome?")
// window.alert("Olá "+ nome + "Seja bem vindo." )
var numero1 = Number(window.prompt ("Digite um numero")) 
var numero2 = Number(window.prompt("Digite outro numero")) 
window.alert(typeof numero1)